language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install cmake qt5-default -y
script: cmake . -Denable_tests=ON -DCMAKE_BUILD_TYPE=Debug && make && make test
