language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install qt5-default -y
  - wget http://www.cmake.org/files/v3.0/cmake-3.0.2-Linux-i386.tar.gz
  - tar xzf cmake-3.0.2-Linux-i386.tar.gz
script: ./cmake-3.0.2-Linux-i386/bin/cmake . -Denable_tests=ON -DCMAKE_BUILD_TYPE=Debug && make && make test
