language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install qt5-default -y
before_script:
  - wget http://www.cmake.org/files/v3.0/cmake-3.0.2.tar.gz -O /tmp/cmake.tar.gz
  - pushd .
  - cd /tmp
  - tar xzf cmake.tar.gz
  - cd cmake-3.0.2
  - ./bootstrap && make && sudo make install
  - popd
script:  cmake . -Denable_tests=ON -DCMAKE_BUILD_TYPE=Debug && make && make test
